steps:
  - name: "gcr.io/cloud-builders/go"
    args: ["install", "github.com/{GITHUB_HANDLE}/gcp-spin-cd"]
    env: ["PROJECT_ROOT=github.com/{GITHUB_HANDLE}/gcp-spin-cd"]
  - name: "gcr.io/cloud-builders/docker"
    args: ["build", "-t", "gcr.io/spinnaker-252016/gcp-spin-cd:$REVISION_ID", "-f", "Dockerfile", "."]
images:
  - "gcr.io/spinnaker-252016/gcp-spin-cd:$REVISION_ID"