apiVersion: apps/v1
kind: Deployment
metadata:
   name: go-dep
spec:
  replicas: 3
  selector:
    matchLabels:
      app: go
  template:
    metadata:
       labels:
          app: go
    spec:
      containers:
      - name: go
        image: skamalj/gcp-cd-codelab
        ports: 
          - containerPort: 80